Feature/bugfinder backend
Gamify-IT/bugfinder-backend pull request #1
Opened 2022-09-12 08:24 UTC by IlijazM

2022-09-13 09:41 UTC, LeviUniAcc reviewed
i checked the licenses, no one is missing

2022-09-13 09:41 UTC, LeviUniAcc commented on .github/workflows/deploy-docker-image-on-release.yml
> +      - "feature/bugfinder-backend"
```suggestion

```

2022-09-13 09:41 UTC, LeviUniAcc commented on .github/workflows/test.yml
> +      - "**"
```suggestion
      - "main"
```

2022-09-13 09:41 UTC, LeviUniAcc commented on .nginx/compose/nginx-dev.conf
> +    }
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on .nginx/compose/nginx.conf
> +    }
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on docker-compose-dev.yaml
> +      - POSTGRES_URL=postgresql://postgres:postgres@login-db:5432/
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on docker-compose-dev.yaml
> +      - POSTGRES_PASSWORD=postgres
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on docker-compose-dev.yaml
> +      - "80"
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on docker-compose.yaml
> +      - POSTGRES_PASSWORD=postgres
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on docker-compose.yaml
> +      - POSTGRES_URL=postgresql://postgres:postgres@login-db:5432/
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on docker-compose.yaml
> +      - "80"
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/ExceptionHandlingController.java
> +  }
what is this?, if unuesd plase remove
```suggestion
  }
```

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/code/CodeDTO.java
> +
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/code/CodeService.java
> +  }
pls add comments

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/code/word/WordDTO.java
> +
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/code/word/WordService.java
> +  }
pls add comments

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/configuration/ConfigurationService.java
> +  }
pls add comments

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/solution/SolutionService.java
> +  }
pls add comments

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugDTO.java
> +
```suggestion
```

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugService.java
> +  }
pls add comments

2022-09-13 09:41 UTC, LeviUniAcc commented on src/main/java/de/unistuttgart/bugfinder/util/UuidUtil.java
> +  }
pls add comment

2022-09-13 10:10 UTC, LeviUniAcc reviewed
cant test until backend is integrated

2022-09-13 10:10 UTC, LeviUniAcc commented on docker-compose.yaml
> +  ## TODO: insert bugfinder backend when ready
why is this not inserted?

2022-09-13 19:16 UTC, madebyTimo commented on .github/workflows/test.yml
> +      - "**"
test should run always

2022-09-18 15:30 UTC, delvh requested changes
Ouch. Please split it into smaller PRs next time…

2022-09-18 15:30 UTC, delvh commented on .github/workflows/deploy-docker-image-on-release.yml
> +      - "v*"
```suggestion
      - "*"
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/ErrorType.java
> +  PRAGMATIC,
```suggestion
  UNDEFINED,
  /**
   * Syntactically allowed, but makes no sense in this context.<br>
   * For example: {@code int i = "Hi";}
   */
  STATIC_SEMANTIC,
  /**
   * Cannot be compiled under any circumstance.<br>
   * For example: {@code if ;<>}
   */
  SYNTAX,
  /**
   * (Undetected) runtime errors after a successful compilation.<br>
   * For example: {@code String s; s.length();}
   */
  DYNAMIC_SEMANTIC,
  /**
   * Strings that can <strong>never</strong> occur outside of a string literal.<br>
   * For example: {@code class 4LeggedAnimal} in Java
   */
  LEXICAL,
  /**
   * Your logic is wrong. Everything compiles and runs, but it doesn't produce the result you wanted.<br>
   * For example: {@code /* increment i */ i--; }
   */
  PRAGMATIC,
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/ErrorType.java
> +public enum ErrorType {
```suggestion
/**
 * Defines the possible error types an error can have.
 */
public enum ErrorType {
```

2022-09-18 15:30 UTC, delvh commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
Where do we use contextually created hibernate LOBs?
Or why was this necessary?

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugMapper.java
> +    return bug.isEmpty() ? Optional.empty() : Optional.of(toDTO(bug.get()));
```suggestion
    return bugs.parallelStream().map(this::toDTO).collect(Collectors.toList());
  }

  public Optional<BugDTO> toDTO(final Optional<Bug> bug) {
    return bug.flatMap(this::toDTO);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugMapper.java
> +    return bugDTO.isEmpty() ? Optional.empty() : Optional.of(fromDTO(bugDTO.get()));
```suggestion
    return bugDTOs.parallelStream().map(this::fromDTO).collect(Collectors.toList());
  }

  public Optional<Bug> fromDTO(final Optional<BugDTO> bugDTO) {
    return bugDTO.flatMap(this::fromDTO);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugDTO.java
> +
No?

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/SolutionMapper.java
> +    return solutionDTO.isEmpty() ? Optional.empty() : Optional.of(fromDTO(solutionDTO.get()));
```suggestion
    return solutionDTOs.parallelStream().map(this::fromDTO).collect(Collectors.toList());
  }

  public Optional<Solution> fromDTO(final Optional<SolutionDTO> solutionDTO) {
    return solutionDTO.flatMap(this::fromDTO);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/SolutionMapper.java
> +    return solution.isEmpty() ? Optional.empty() : Optional.of(toDTO(solution.get()));
```suggestion
    return solutions.parallelStream().map(this::toDTO).collect(Collectors.toList());
  }

  public Optional<SolutionDTO> toDTO(final Optional<Solution> solution) {
    return solution.flatMap(this::toDTO);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugService.java
> +    log.info("delete bug {}", id);
```suggestion
    log.debug("get all bugs");
    return bugMapper.toDTO(bugRepository.findAll());
  }

  public Optional<BugDTO> find(final UUID id) {
    log.debug("get bug {}", id);
    return bugMapper.toDTO(bugRepository.findById(id));
  }

  public BugDTO save(final BugDTO bugDTO) {
    log.info("create bug {}", bugDTO);
    return bugMapper.toDTO(bugRepository.save(bugMapper.fromDTO(bugDTO)));
  }

  public void delete(final UUID id) {
    log.debug("delete bug {}", id);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugMapper.java
> +      wordRepository.findById(bugDTO.getWordId()).orElseThrow(),
```suggestion
      wordRepository.findById(bugDTO.getWordId()).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, String.format("word %s does not exist", bugDTO.getWordId()))),
```
Or do you have a better idea than a `404` here? It is somewhat fitting, but is there something better?

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/SolutionService.java
> +    return bugMapper.toDTO(solution.getBugs());
```suggestion
    log.debug("get all solutions");
    return solutionMapper.toDTO(solutionRepository.findAll());
  }

  public Optional<SolutionDTO> find(final UUID id) {
    log.debug("get solution {}", id);
    return solutionMapper.toDTO(solutionRepository.findById(id));
  }

  public SolutionDTO save(final SolutionDTO solutionDTO) {
    log.debug("create solution {}", solutionDTO);
    return solutionMapper.toDTO(solutionRepository.save(solutionMapper.fromDTO(solutionDTO)));
  }

  public void delete(final UUID id) {
    log.debug("delete solution {}", id);
    solutionRepository.deleteById(id);
  }

  public BugDTO addBug(final UUID id, final BugDTO bug) {
    log.debug("add bug {} to solution {}", bug, id);
    final Solution solution = solutionRepository
      .findById(id)
      .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, String.format("Unable to find solution with id %s", id))
      );
    final BugDTO savedBug = bugService.save(bug);
    solution.addBug(bugMapper.fromDTO(savedBug));
    solutionRepository.save(solution);
    return savedBug;
  }

  public BugDTO removeBug(final UUID id, final UUID bugId) {
    log.debug("remove bug {} from solution {}", bugId, id);
    final Solution solution = solutionRepository
      .findById(id)
      .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, String.format("Unable to find solution with id %s", id))
      );
    final BugDTO bug = bugService
      .find(bugId)
      .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, String.format("Unable to find bug with id %s", id)));
    solution.removeBug(bugMapper.fromDTO(bug));
    solutionRepository.save(solution);
    return bug;
  }

  public List<BugDTO> getBugs(final UUID id) {
    log.debug("get bugs from solution {}", id);
    final Solution solution = solutionRepository
      .findById(id)
      .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, String.format("Unable to find solution with id %s", id))
      );
    return bugMapper.toDTO(solution.getBugs());
```

2022-09-18 15:30 UTC, delvh commented on README.md
> +This repo serves to persist the bugfinder data in a db and to communicate with different Microservices.
```suggestion
The bugfinder backend stores the data of bugfinder instances and communicates results with the overworld backend.
```

2022-09-18 15:30 UTC, delvh commented on README.md
> +- Docker: [Docker latest or higher](https://www.docker.com/)
```suggestion
- Docker: [Docker](https://www.docker.com/)
```
Sounded a bit weird…

2022-09-18 15:30 UTC, delvh commented on README.md
> +file. If you changed the properties of the postgres db, you also have to change spring.datasource.url.
```suggestion
Firstly, you have to change the `spring.datasource.username` and the `spring.datasource.password` in the `application.properties` file.
Then, if you changed the postgres URL/ port, you also have to change `spring.datasource.url`.
```

2022-09-18 15:30 UTC, delvh commented on README.md
> +the [manual for starting the dependencies with docker-compose](https://github.com/Gamify-IT/docs/blob/main/dev-manuals/docker-compose/docker-compose.md)
>  The 'Gamify-IT/docs' repository doesn't contain the 'dev-manuals/docker-compose/docker-compose.md' path in 'main'.

2022-09-18 15:30 UTC, delvh commented on README.md
> +And run it at port 8000 with
```suggestion
And run it on port `8000` with
```

2022-09-18 15:30 UTC, delvh commented on README.md
> +To stop and remove it simply type
```suggestion
To stop and remove it, use
```

2022-09-18 15:30 UTC, delvh commented on docker-compose-dev.yaml
> +  #     - "80"
?

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/BugfinderServiceApplication.java
> +@SpringBootApplication(scanBasePackages = { "de.unistuttgart" })
```suggestion
@SpringBootApplication
```
Becomes obsolete once `authentication-validator@v0.0.2` is released

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/code/Code.java
> +public class Code {
We **certainly** need documentation here.
You can't have uncommented code defining a code object without boggling your readers mind.

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/Bug.java
> +  ErrorType errorType;
```suggestion
  @Enumerated
  ErrorType errorType;
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +            log.warn(warning + notFound);
```suggestion
            log.warn(warning, badGateway);
            throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE, warning);
        } catch (FeignException.NotFound notFound) {
            String warning = String.format("The result could not be saved. Unknown User '%s'.", userId);
            log.warn(warning, notFound);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/Solution.java
> +  }
```suggestion
  public void addBug(final Bug... bugs) {
    this.bugs.addAll(bugs);
  }

  public void removeBugs(final Bug... bugs) {
    this.bugs.removeAll(bugs);
  }
```
I've noticed this already in another of the data classes as well, I just don't know where anymore.

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/Solution.java
> +public class Solution {
This is another instance where documentation is really needed.

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugDTO.java
> +  ErrorType errorType;
```suggestion

    @Enumerated
    ErrorType errorType;
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/Bug.java
> +  @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
`ManyToOne`?
You can have multiple bugs per word?
Don't you mean `OneToOne`, and shouldn't this even be an `Optional`?

2022-09-18 15:30 UTC, delvh commented on pom.xml
> +        </dependency>
Uhmm… Why?

2022-09-18 15:30 UTC, delvh commented on pom.xml
> +            <version>3.1.4</version>
Please be consistent with the properties, and make these versions properties as well.

2022-09-18 15:30 UTC, delvh commented on pom.xml
> +        </dependency>
Are you even using that? You wrote all mappers yourself, right?

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/ExceptionHandlingController.java
> +  }
```suggestion
```
I agree with @LeviUniAcc.

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +                "BUGFINDER",
It will always be bugfinder, right?
So please just ensure it inside the class, so that callers don't need to guess what is expected.

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +                    "The Overworld backend is currently not available. The result was NOT saved. Please try again later";
```suggestion
                    "The Overworld backend is currently not available. The result was NOT saved. Please try again later.";
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/SolutionRepository.java
> +  @Query("select s from Solution s where s.code.id = :codeId")
Did the queries accept JPQL?
Or does it have to be SQL?
Because this seems like JPQL…

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/configuration/ConfigurationService.java
> +    return codeMapper.toDTO(configuration.getCodes());
```suggestion
    log.debug("get all configurations");
    return configurationMapper.toDTO(configurationRepository.findAll());
  }

  public Optional<ConfigurationDTO> find(final UUID id) {
    log.debug("get configuration {}", id);
    return configurationMapper.toDTO(configurationRepository.findById(id));
  }

  public ConfigurationDTO save(final ConfigurationDTO configurationDTO) {
    log.debug("create configuration {}", configurationDTO);
    return configurationMapper.toDTO(configurationRepository.save(configurationMapper.fromDTO(configurationDTO)));
  }

  /**
   * Deletes the configuration with the given ID, if present.
   *
   * @param id the ID of the configuration to delete
   * @return the deleted configuration, if found
   * @throws ResponseStatusException (204 - NO_CONTENT) if the configuration was not found
   */
  public ConfigurationDTO delete(final UUID id) {
    log.info("delete configuration {}", id);
    Configuration configuration = configurationRepository
      .findById(id)
      .orElseThrow(() -> new ResponseStatusException(HttpStatus.NO_CONTENT)));
    configurationRepository.deleteById(id);
    return configurationMapper.toDTO(configuration);
  }

  public CodeDTO addCode(final UUID id, final CodeDTO code) {
    log.debug("add code {} to configuration {}", code, id);
    final Configuration configuration = getConfiguration(id);
    final CodeDTO savedCode = codeService.save(code);
    configuration.addCode(codeMapper.fromDTO(savedCode));
    configurationRepository.save(configuration);
    return savedCode;
  }

  public CodeDTO removeCode(final UUID id, final UUID codeId) {
    log.debug("remove code {} from configuration {}", codeId, id);
    final Configuration configuration = getConfiguration(id);
    final CodeDTO persistedCode = codeService
      .find(codeId)
      .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, String.format("Unable to find code with id %s", id)));
    configuration.removeCode(codeMapper.fromDTO(persistedCode));
    configurationRepository.save(configuration);
    return persistedCode;
  }

  public List<CodeDTO> getCodes(final UUID id) {
    log.debug("get codes from configuration {}", id);
    return codeMapper.toDTO(getConfiguration(id).getCodes());
  }
    
  /**
   * @return the configuration with the given ID
   * @throws ResponseStatusException (404) if no configuration with this ID exists
   */
  private Configuration getConfiguration(final UUID id) {
    return configurationRepository
      .findById(id)
      .orElseThrow(() ->
        new ResponseStatusException(NOT_FOUND, String.format("Unable to find configuration with id %s", id))
      );
    }
```
Regarding the change in the delete method: No need to throw a `404` if all you want to do is deleting it…

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/configuration/ConfigurationMapper.java
> +    return configurationDTO.isEmpty() ? Optional.empty() : Optional.of(fromDTO(configurationDTO.get()));
```suggestion
    return codes.parallelStream().map(this::toDTO).collect(Collectors.toList());
  }

  public Optional<ConfigurationDTO> toDTO(final Optional<Configuration> configuration) {
    return configuration.flatMap(this::toDTO);
  }

  public Configuration fromDTO(final ConfigurationDTO configurationDTO) {
    return new Configuration(configurationDTO.getId(), new HashSet<>(codeMapper.fromDTO(configurationDTO.getCodes())));
  }

  public List<Configuration> fromDTO(final List<ConfigurationDTO> codeDTOs) {
    return codeDTOs.parallelStream().map(this::fromDTO).collect(Collectors.toList());
  }

  public Optional<Configuration> fromDTO(final Optional<ConfigurationDTO> configurationDTO) {
    return configurationDTO.flatMap(this::fromDTO);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/code/word/WordMapper.java
> +    return wordDTO.isEmpty() ? Optional.empty() : Optional.of(fromDTO(wordDTO.get()));
```suggestion
    return words.parallelStream().map(this::toDTO).collect(Collectors.toList());
  }

  public Optional<WordDTO> toDTO(final Optional<Word> word) {
    return word.flatMap(this::toDTO);
  }

  public Word fromDTO(final WordDTO wordDTO) {
    return new Word(wordDTO.getId(), wordDTO.getWord());
  }

  public List<Word> fromDTO(final List<WordDTO> wordDTOs) {
    return wordDTOs.parallelStream().map(this::fromDTO).collect(Collectors.toList());
  }

  public Optional<Word> fromDTO(final Optional<WordDTO> wordDTO) {
    return wordDTO.flatMap(this::fromDTO);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/code/word/WordService.java
> +    log.info("delete word {}", id);
```suggestion
    log.debug("get all words");
    return wordMapper.toDTO(wordRepository.findAll());
  }

  public Optional<WordDTO> find(final UUID id) {
    log.debug("get word {}", id);
    return wordMapper.toDTO(wordRepository.findById(id));
  }

  public WordDTO save(final WordDTO wordDTO) {
    log.debug("create word {}", wordDTO);
    return wordMapper.toDTO(wordRepository.save(wordMapper.fromDTO(wordDTO)));
  }

  public void delete(final UUID id) {
    log.debug("delete word {}", id);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/configuration/Configuration.java
> +public class Configuration {
And another class to document.

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/code/word/WordDTO.java
> +
Again, disagreed.

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/code/CodeDTO.java
> +
No!

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/code/CodeMapper.java
> +    return codeDTO.isEmpty() ? Optional.empty() : Optional.of(fromDTO(codeDTO.get()));
```suggestion
    return codes.parallelStream().map(this::toDTO).collect(Collectors.toList());
  }

  public Optional<CodeDTO> toDTO(final Optional<Code> code) {
    return code.flatMap(this::toDTO);
  }

  public Code fromDTO(final CodeDTO codeDTO) {
    return new Code(codeDTO.getId(), wordMapper.fromDTO(codeDTO.getWords()));
  }

  public List<Code> fromDTO(final Collection<CodeDTO> codeDTOs) {
    return codeDTOs.parallelStream().map(this::fromDTO).collect(Collectors.toList());
  }

  public Optional<Code> fromDTO(final Optional<CodeDTO> codeDTO) {
    return codeDTO.flatMap(this::fromDTO);
```

2022-09-18 15:30 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/code/CodeService.java
> +  }
```suggestion
    log.debug("get all codes");
    return codeMapper.toDTO(codeRepository.findAll());
  }

  public Optional<CodeDTO> find(final UUID id) {
    log.debug("get code {}", id);
    return codeMapper.toDTO(codeRepository.findById(id));
  }

  public CodeDTO save(final CodeDTO codeDTO) {
    log.debug("create code {}", codeDTO);
    return codeMapper.toDTO(codeRepository.save(codeMapper.fromDTO(codeDTO)));
  }

  public void delete(final UUID id) {
    log.debug("delete code {}", id);
    codeRepository.deleteById(id);
  }

  public WordDTO addWord(final UUID id, final WordDTO word) {
    log.debug("add word {} to code {}", word, id);
    final Code code = getCode(id);
    final WordDTO savedWord = wordService.save(word);
    code.addWord(wordMapper.fromDTO(savedWord));
    codeRepository.save(code);
    return savedWord;
  }

  public WordDTO removeWord(final UUID id, final UUID wordId) {
    log.debug("remove word {} from code {}", wordId, id);
    final Code code = getCode(id);
    final WordDTO word = wordService
      .find(wordId)
      .orElseThrow(() -> new ResponseStatusException(HttpStatus.NO_CONTENT));
    code.removeWord(wordMapper.fromDTO(word));
    codeRepository.save(code);
    return word;
  }

  public List<WordDTO> getWords(final UUID id) {
    log.debug("get words from code {}", id);
    return wordMapper.toDTO(getCode(id).getWords());
  }

  public SolutionDTO getSolution(final UUID id) {
    log.debug("get solution with id {}", id);
    return solutionMapper.toDTO(
      solutionRepository
        .findByCodeId(id)
        .orElseThrow(() ->
          new ResponseStatusException(NOT_FOUND, String.format("Unable to find solution with id %s", id))
        )
    );
  }
  
  /**
   * @return the configuration with the given ID
   * @throws ResponseStatusException (404) if no configuration with this ID exists
   */
   private Code getCode(final UUID id) {
     return codeRepository
      .findById(id)
      .orElseThrow(() -> new ResponseStatusException(NOT_FOUND, String.format("Unable to find code with ID %s", id)));
   }
```

2022-09-19 12:31 UTC, maexled commented
please re-review

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/bug/BugMapper.java
> +      wordRepository.findById(bugDTO.getWordId()).orElseThrow(),
Still relevant.

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultController.java
> +@Import({ JWTValidatorService.class })
Will be unnecessary with `authenticationvalidator@v1.0.0`, which is already released.

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +    return totalScore / codeScore.size();
```suggestion
    return map.values().parallelStream().mapToLong(l -> l).filter(score -> score <= MAX_SCORE && score >= 0).average().orElse(MAX_SCORE);
```
Handles even the edge cases that there is no question, or invalid values, correctly…

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +    );
```suggestion
    return playersSolution
      .getBugs()
      .parallelStream()
      .filter(playerBug -> Objects.equals(playerBug.getWordId(), bug.getWord().getId()))
      .filter(playerBug -> playerBug.getErrorType() == bug.getErrorType())
      .map(Bug::getCorrectValue)
      .anyMatch(Predicate.isEqual(bug.getCorrectValue()));
```

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +    List<SubmittedSolutionDTO> submittedSolutions,
```suggestion
    Collection<SubmittedSolutionDTO> submittedSolutions,
```

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +        0
```suggestion
          .noneMatch(bug -> bug.getWord().getId().equals(playerBug.getWordId()))
```

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +    return 0l;
```suggestion
    final Optional<Solution> solution = solutionRepository.findByCodeId(code.getId());
    if (solution.isEmpty()) {
      // if no solution is provided, give the player full points
      return MAX_SCORE;
    }
     final Optional<SubmittedSolutionDTO> playerSubmittedSolution = getSubmittedSolutionFromCode(
        gameResultDTO.getSubmittedSolutions(),
        code
      );
      if (playerSubmittedSolution.isEmpty()) {
        return 0L;
      }
      
      final SolutionDTO playerSolution = playerSubmittedSolution.get().getSolution();
      final int bugsSolved = solution.get().getBugs().parallelStream().filter(bug -> fixedBug(bug, playerSolution)).count();
      final List<BugDTO> falseSubmittedBugs = getFalseSubmittedBugs(solution.get(), playerSolution);
      final int bugsMissolved = falseSubmittedBugs.size();
      
      long score;
        if (solution.get().getBugs().isEmpty() && bugsMissolved == 0) {
          score = MAX_SCORE;
        } else {
          score = (Math.max(bugsSolved - bugsMissolved, 0) / Math.max(solution.get().getBugs().size(), 1)) * MAX_SCORE;
        }
        
        log.debug("Solved {}/{} bugs, and falsely solved {} bugs", bugsSolved, solution.get().getBugs().size(), bugsMissolved);
        log.debug("Reached score of {} on code with ID {}", score, code.getId());
        return score;
```

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +        )
Can we please offload this block into a method, that only takes one parameter, the ID to load?
I've seen this call **way** to often.

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +    return calculateScoreFromCodeScores(codeScore);
```suggestion
    final long score = calculateScoreFromCodeScores(codeScore);
    log.debug(
      "Player got score of {} in configuration with ID {}",
      score,
      configuration.getId()
    );
    return score;
```

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +    }
The previous messages I wrote about this block still apply.

2022-09-19 15:12 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/configuration/ConfigurationService.java
> +      );
You have the method above, simply extract everything except the mapper part, and you have it already!

2022-09-19 15:19 UTC, delvh commented
You forgot quite a few of my previous suggestions.

2022-09-19 18:37 UTC, delvh commented on README.md
> +the [manual for starting the dependencies with docker-compose](https://github.com/Gamify-IT/docs/blob/main/dev-manuals/docker-compose/docker-compose.md)
still applies. fix the link please.

2022-09-19 18:37 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +    List<SubmittedSolutionDTO> submittedSolutions,
Okay, I can understand this one.

2022-09-19 18:37 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +    );
I disagree that this one should be less readable.
I mean, the current approach uses repeated `Optional#get`. That's most often a sign that something is wrong with your logic.

2022-09-19 18:37 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/solution/Solution.java
> +  }
I mean…
Yes, I can somewhat understand it why it doesn't look good.
However, there might be an exception here:
If Hibernate behaves like I think it does, adding or removing multiple bugs will have serious performance implications.

2022-09-19 18:37 UTC, delvh commented on src/main/java/de/unistuttgart/bugfinder/gameresult/GameResultService.java
> +      "BUGFINDER",
The last thing I have to criticize is that the `OverworldResultDTO` is responsible for ensuring the string is `BUGFINDER` in **all** cases, and that callers should not need to guess what string is expected.
So, either ensure this in the constructor, or if you know of any annotation for it use that.

2022-09-19 20:32 UTC, delvh approved these changes

2022-09-20 21:07 UTC, Gr33ndev approved these changes

2022-09-20 21:08 UTC, merged